### ISSUE TITLE
Save licenses to erc.yml

### ISSUE THREAD

**Issue by nuest** [o2r-project/o2r-muncher#91]
See http://o2r.info/erc-spec/spec/#license-metadata

Target structure:

```yml
    licenses:
        code: Apache-2.0
        data: ODbL-1.0
        text: CC0-1.0
        ui_bindings: CC0-1.0
        metadata: CC0-1.0
```
